angular.module("springboardApp")
.controller("mainController",MainController)
.controller("homeController",HomeController)
.controller("pathListController",PathListController)
.controller("pathDetailsController",PathDetailsController)